config/routes.rb
Rails.application.routes.draw do
  resources :tarefas do
    collection do
      get :atualizar_status
    end
  end

  resources :acoes do
    resources :etapas
    get 'relatorio', on: :member, defaults: { format: :pdf }
    get 'relatorio_geral', on: :collection, defaults: { format: :pdf }
    get 'relatorio_geral_simplificado', on: :collection, defaults: { format: :pdf }
  end
  
  namespace :transporte_escolar do
    resources :servicos do
      collection do
        post :search
      end
    end
  end
  namespace :transporte_escolar do
    resources :contratos
  end
  namespace :transporte_escolar do
    resources :veiculos
  end
  namespace :transporte_escolar do
    resources :condutores
  end
  namespace :transporte_escolar do
    resources :transportadores
  end
  namespace :transporte_escolar do
    resources :escolas
  end
  namespace :transporte_escolar do
    resources :municipios
  end
  resources :incidentes do
    member do
      get 'finalizar'
      put 'salvar'
    end
  end

  resources :mensagens do
    get 'mensagens_diretas', on: :collection
    get 'refresh', on: :collection
    post 'js_create', on: :collection
    member do
      get 'new_image'
      put 'update_image'
    end
    get 'imagem', on: :collection
  end

  resources :autocompletes, only: [] do
    collection do
      get :problemas_ti
      get :cargos
      get :funcoes
      get :unidades
      get :usuarios
      get :estados
      get :municipios
      get :permissoes_drive
      get :perfis
    end
  end

  resources :cargos
  resources :tipo_unidades
  resources :problema_tis
  resources :tipo_problema_tis
  resources :equipamentos do
    member do
      patch :transferir
      patch :alterar_status
      patch :remover_de_kit
    end
    collection do
      get :buscar
      get :relatorio
      get :verificar_kit
      get :exportar_excel
      get :autocomplete_marcas
      get :autocomplete_modelos
      get :autocomplete_identificacoes_kit
      get :autocomplete_contratos
      get :autocomplete_processos
    end
  end

  resources :movimentacao_equipamentos do
    member do
      patch :receber_equipamento
      patch :cancelar
    end
    collection do
      get :buscar_equipamentos
      get :buscar_usuarios_unidade
    end
  end
  resources :requisicao_tis do
    member do
      get 'finalizar'
      put 'salvar'
    end
  end

  namespace :nuinfo do
    resources :requisicao_tis, only: [:index, :show] do
      get 'pegar'
      collection do
        get 'acompanhamento'
        get 'refresh_acompanhamento'
        get 'em_atendimento'
        get 'estatisticas'
        post 'buscar_estatisticas'
      end
      member do
        get 'concluir'
        get 'trocar_tecnico'
        put 'salvar'
        put 'salvar_troca_tecnico'
      end
    end
  end

  get 'patio/index'
  get 'patio/entrada'
  get 'patio/saida'

  namespace :useget do
    resources :requisicao_transportes, only: [:index, :show] do
      get 'aprovar'
      member do
        get 'reagendar'
        put 'salvar_reagendamento'
      end
      collection do
        get 'acompanhamento'
        get 'refresh_acompanhamento'
      end
      member do
        get 'negar'
        put 'salvar_negacao'
      end
    end
  end

  resources :servico_transportes, only: [:show, :new, :create, :edit, :update]

  resources :destinos
  resources :passageiros
  resources :requisicao_transportes do
    member do
      get 'avaliar_reagendamento'
      put 'aprovar_reagendamento'
      put 'negar_reagendamento'
    end
  end
  resources :veiculos
  resources :motoristas
  get 'home/index'

  get 'perfil/index'
  put 'perfil/update'
  get 'perfil/alterar_senha'
  put 'perfil/salvar_senha'

  resources :usuarios do
    member do
      get 'resetar_senha'
      get 'tornar_requisitante_transporte'
      get 'tornar_tecnico_transporte'
    end
  end

  resources :unidades
  resources :funcoes do
    get 'autocomplete', on: :collection
  end

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/controllers/movimentacao_equipamentos_controller.rb
class MovimentacaoEquipamentosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movimentacao, only: [:show, :receber_equipamento, :cancelar]
  before_action :authorize_movimentacao

  def index
    base_scope = if current_user.has_role?(:tec_serv_ti)
      # Técnicos veem todas as movimentações (exceto iniciais)
      MovimentacaoEquipamento.sem_iniciais
    elsif current_user.has_role?(:req_serv_ti)
      # Usuários req_serv_ti veem apenas movimentações onde são responsáveis e em andamento
      MovimentacaoEquipamento.por_responsavel(current_user.id).em_andamento.sem_iniciais
    else
      MovimentacaoEquipamento.none
    end

    @unidades = Unidade.order(:nome)
    @usuarios = User.order(:nome)

    @movimentacoes = aplicar_filtros(base_scope)
                      .includes(:unidade_origem, :unidade_destino, :responsavel, :user, :item_movimentacoes)
                      .order(created_at: :desc)
                      .page(params[:page])
                      .per(20)
  end

  def new
    @movimentacao = MovimentacaoEquipamento.new
    @unidades = Unidade.order(:nome)
    @usuarios = User.joins(:roles).where(roles: { name: 'req_serv_ti' }).order(:nome)
  end

  def create
    @movimentacao = MovimentacaoEquipamento.new(movimentacao_params)
    @movimentacao.user = current_user # Criador da movimentação

    if @movimentacao.save
      # Adicionar equipamentos selecionados
      equipamentos_nao_adicionados = []
      
      if params[:equipamento_ids].present?
        params[:equipamento_ids].each do |equipamento_id|
          equipamento = Equipamento.find(equipamento_id)
          unless @movimentacao.adicionar_equipamento(equipamento)
            equipamentos_nao_adicionados << equipamento.nome_completo
          end
        end
      end

      if equipamentos_nao_adicionados.any?
        flash[:warning] = "Movimentação criada com sucesso! Alguns equipamentos não puderam ser adicionados pois já estão em movimentação: #{equipamentos_nao_adicionados.join(', ')}"
      else
        flash[:success] = 'Movimentação criada com sucesso!'
      end
      
      redirect_to movimentacao_equipamentos_path
    else
      @unidades = Unidade.order(:nome)
      @usuarios = User.joins(:roles).where(roles: { name: 'req_serv_ti' }).order(:nome)
      flash.now[:error] = 'Erro ao criar movimentação.'
      render :new
    end
  end

  def show
    @item_movimentacoes = @movimentacao.item_movimentacoes.includes(:equipamento)
  end

  def receber_equipamento
    equipamento = Equipamento.find(params[:equipamento_id])
    
    if @movimentacao.status == 'em_andamento' && @movimentacao.receber_equipamento(equipamento, current_user)
      flash[:success] = "Equipamento '#{equipamento.nome_completo}' recebido com sucesso!"
    else
      flash[:error] = "Erro ao receber equipamento."
    end

    redirect_to movimentacao_equipamento_path(@movimentacao)
  end

  def cancelar
    if @movimentacao.cancelar_movimentacao(current_user)
      flash[:success] = "Movimentação cancelada com sucesso!"
    else
      if @movimentacao.equipamentos_recebidos_count > 0
        flash[:error] = "Não é possível cancelar uma movimentação que já possui equipamentos recebidos."
      elsif @movimentacao.user != current_user
        flash[:error] = "Apenas o criador da movimentação pode cancelá-la."
      else
        flash[:error] = "Erro ao cancelar movimentação."
      end
    end

    redirect_to movimentacao_equipamentos_path
  end

  def buscar_equipamentos
    unidade_id = params[:unidade_id]
    
    if unidade_id.present?
      # Buscar equipamentos da unidade (todos) e marcar bloqueados se estiverem em movimentação em andamento
      equipamentos_scope = Equipamento.where(unidade_id: unidade_id, tipo: 'individual')
                                       .includes(:unidade)
                                       .order(:tipo_equipamento, :marca, :modelo)

      # itens bloqueados por movimentações em andamento (pegar o mais recente por equipamento)
      itens_bloqueados = ItemMovimentacao
                           .joins(:movimentacao_equipamento)
                           .where(status: 'pendente')
                           .where(movimentacao_equipamentos: { status: 'em_andamento' })
                           .includes(movimentacao_equipamento: [:unidade_destino, :responsavel])

      bloqueado_por_equip = {}
      itens_bloqueados.each do |item|
        atual = bloqueado_por_equip[item.equipamento_id]
        if atual.nil? || (atual.movimentacao_equipamento.created_at < item.movimentacao_equipamento.created_at)
          bloqueado_por_equip[item.equipamento_id] = item
        end
      end

      @equipamentos = equipamentos_scope.map do |e|
        item_bloq = bloqueado_por_equip[e.id]
        bloqueado = item_bloq.present?
        unidade_label = nil
        responsavel_curto = nil
        if bloqueado
          mov = item_bloq.movimentacao_equipamento
          unidade = mov.unidade_destino
          begin
            if unidade&.tipo_unidade&.nome == 'ESCOLA'
              unidade_label = unidade.nome
            else
              unidade_label = unidade.respond_to?(:sigla_nome) ? unidade.sigla_nome : unidade.nome
            end
          rescue
            unidade_label = unidade&.nome
          end
          resp_nome = mov.responsavel&.nome.to_s.strip
          if resp_nome.present?
            partes = resp_nome.split
            responsavel_curto = partes.size > 1 ? "#{partes.first} #{partes.last}" : partes.first
          end
        end

        {
          id: e.id,
          nome: e.respond_to?(:nome_completo) ? e.nome_completo : e.modelo || e.marca || e.id,
          tipo_equipamento: e.tipo_equipamento,
          marca: e.marca,
          modelo: e.modelo,
          numero_serial: e.numero_serial,
          numero_patrimonio: e.numero_patrimonio,
          contrato: e.contrato,
          processo: e.processo,
          bloqueado: bloqueado,
          unidade_destino_label: unidade_label,
          responsavel_curto: responsavel_curto
        }
      end
    else
      @equipamentos = []
    end

    respond_to do |format|
      format.json { render json: @equipamentos }
    end
  end

  def buscar_usuarios_unidade
    unidade_id = params[:unidade_id]
    
    if unidade_id.present?
      @usuarios = User.joins(:roles)
                     .where(unidade_id: unidade_id, roles: { name: 'req_serv_ti' })
                     .order(:nome)
    else
      @usuarios = []
    end

    respond_to do |format|
      format.json { render json: @usuarios.map { |u| { id: u.id, nome: u.nome } } }
    end
  end

  private

  def set_movimentacao
    @movimentacao = MovimentacaoEquipamento.includes(:unidade_origem, :unidade_destino, :responsavel, :user).find(params[:id])
  end

  def authorize_movimentacao
    case action_name
    when 'index'
      # Pode ver se é tec_serv_ti ou se é req_serv_ti
      unless current_user.has_role?(:tec_serv_ti) || current_user.has_role?(:req_serv_ti)
        redirect_to home_index_path, alert: 'Você não tem permissão para acessar esta área.'
      end
    when 'show'
      # Pode ver se é tec_serv_ti ou se é req_serv_ti e é responsável
      unless current_user.has_role?(:tec_serv_ti) || 
             (current_user.has_role?(:req_serv_ti) && 
              MovimentacaoEquipamento.por_responsavel(current_user.id).exists?(id: params[:id]))
        redirect_to home_index_path, alert: 'Você não tem permissão para acessar esta área.'
      end
    when 'new', 'create'
      # Só tec_serv_ti pode criar
      unless current_user.has_role?(:tec_serv_ti)
        redirect_to home_index_path, alert: 'Você não tem permissão para criar movimentações.'
      end
    when 'receber_equipamento'
      # Só o responsável pode receber
      unless current_user.has_role?(:req_serv_ti) && 
             MovimentacaoEquipamento.por_responsavel(current_user.id).exists?(id: params[:id])
        redirect_to home_index_path, alert: 'Você não tem permissão para receber equipamentos.'
      end
    when 'cancelar'
      # Só o criador pode cancelar
      unless current_user.has_role?(:tec_serv_ti) && 
             MovimentacaoEquipamento.where(user: current_user).exists?(id: params[:id])
        redirect_to home_index_path, alert: 'Você não tem permissão para cancelar esta movimentação.'
      end
    end
  end

  def movimentacao_params
    params.require(:movimentacao_equipamento).permit(:unidade_origem_id, :unidade_destino_id, :responsavel_id, :descricao)
  end

  def aplicar_filtros(relation)
    rel = relation

    # Filtro por unidade (origem ou destino)
    if params[:unidade_id].present?
      unidade_id = params[:unidade_id]
      rel = rel.where("unidade_origem_id = :uid OR unidade_destino_id = :uid", uid: unidade_id)
    end

    # Filtro por status
    if params[:status].present?
      rel = rel.where(status: params[:status])
    end

    # Filtro por criador (user_id)
    if params[:user_id].present?
      rel = rel.where(user_id: params[:user_id])
    end

    # Filtro por responsável
    if params[:responsavel_id].present?
      rel = rel.where(responsavel_id: params[:responsavel_id])
    end

    # Pesquisa textual em atributos de equipamentos relacionados
    if params[:q].present?
      termo = "%#{params[:q].strip}%"
      equipamentos_ids = Equipamento
        .where(
          "marca ILIKE :t OR modelo ILIKE :t OR tipo ILIKE :t OR tipo_equipamento ILIKE :t OR numero_serial ILIKE :t OR numero_patrimonio ILIKE :t OR outra_identificacao ILIKE :t OR descricao ILIKE :t OR contrato ILIKE :t OR processo ILIKE :t OR host ILIKE :t OR ip ILIKE :t OR codigo_kit ILIKE :t OR identificacao_kit ILIKE :t",
          t: termo
        )
        .select(:id)

      rel = rel.joins(:item_movimentacoes).where(item_movimentacoes: { equipamento_id: equipamentos_ids })
    end

    rel.distinct
  end
end

app/helpers/movimentacao_equipamentos_helper.rb
module MovimentacaoEquipamentosHelper
end

app/views/movimentacao_equipamentos/index.html.erb
<% content_for :title do %>
  <i class="fas fa-exchange-alt"></i> Movimentações de Equipamentos
<% end %>

<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active"><a href="<%= movimentacao_equipamentos_url %>">Movimentações</a></li>
<% end %>

<% content_for :sub_title do %>
  Lista de movimentações de equipamentos
<% end %>

<% content_for :buttons do %>
  <% if current_user.has_role?(:tec_serv_ti) %>
    <%= link_to new_movimentacao_equipamento_path, class: "btn btn-sm btn-success", title: "Nova Movimentação" do %>
      <i class="fas fa-plus"></i> Nova Movimentação
    <% end %>
  <% end %>
<% end %>

<div class="card">
  <div class="card-header">
    <h5 class="card-title">
      <% if current_user.has_role?(:tec_serv_ti) %>
        Todas as Movimentações
      <% elsif current_user.has_role?(:req_serv_ti) %>
        Minhas Movimentações Pendentes
      <% end %>
    </h5>
  </div>
  <div class="card-body">
    <div class="card mb-3">
      <div class="card-header">
        <h5 class="card-title">Filtros</h5>
      </div>
      <div class="card-body">
        <%= form_with url: movimentacao_equipamentos_path, method: :get, local: true do %>
          <div class="row">
            <div class="col-md-3 mb-2">
              <label class="form-label">Unidade</label>
              <%= hidden_field_tag :unidade_id, params[:unidade_id], id: 'mov_equip_unidade_id' %>
              <%= text_field_tag :unidade_nome, params[:unidade_nome], class: 'form-control form-control-sm js-autocomplete-unidade', autocomplete: 'off', placeholder: 'Digite para buscar unidade' %>
            </div>
            <div class="col-md-2 mb-2">
              <label class="form-label">Status</label>
              <%= select_tag :status, options_for_select([["Todos",""],["Em andamento","em_andamento"],["Concluída","concluida"],["Cancelada","cancelada"]], params[:status]), class: 'form-control form-control-sm' %>
            </div>
            <div class="col-md-3 mb-2">
              <label class="form-label">Criador</label>
              <%= hidden_field_tag :user_id, params[:user_id], id: 'mov_equip_user_id' %>
              <%= text_field_tag :user_nome, params[:user_nome], class: 'form-control form-control-sm js-autocomplete-usuario-criador', autocomplete: 'off', placeholder: 'Digite para buscar usuário' %>
            </div>
            <div class="col-md-3 mb-2">
              <label class="form-label">Responsável</label>
              <%= hidden_field_tag :responsavel_id, params[:responsavel_id], id: 'mov_equip_responsavel_id' %>
              <%= text_field_tag :responsavel_nome, params[:responsavel_nome], class: 'form-control form-control-sm js-autocomplete-usuario-responsavel', autocomplete: 'off', placeholder: 'Digite para buscar responsável' %>
            </div>
          </div>
          <div class="row mt-2">
            <div class="col-md-4 mb-2">
              <label class="form-label">Buscar Equipamento</label>
              <%= text_field_tag :q, params[:q], class: 'form-control form-control-sm', placeholder: 'Marca, modelo, tipo, serial, patrimônio, contrato, processo...' %>
            </div>
            <div class="col-12">
              <br>
              <button type="submit" class="btn btn-info btn-sm"><i class="fas fa-search"></i> Filtrar</button>
              <%= link_to "Limpar", movimentacao_equipamentos_path, class: "btn btn-secondary btn-sm" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <% if @movimentacoes.any? %>
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>ID</th>
              <th>Origem</th>
              <th>Destino</th>
              <th>Responsável</th>
              <% if current_user.has_role?(:tec_serv_ti) %>
                <th>Criador</th>
              <% end %>
              <th>Status</th>
              <th>Equipamentos</th>
              <th>Data</th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            <% @movimentacoes.each do |movimentacao| %>
              <tr>
                <td><%= movimentacao.id %></td>
                <td><%= movimentacao.unidade_origem.sigla_nome %></td>
                <td><%= movimentacao.unidade_destino.sigla_nome %></td>
                <td><%= movimentacao.responsavel.nome %></td>
                <% if current_user.has_role?(:tec_serv_ti) %>
                  <td><%= movimentacao.user&.nome || 'N/A' %></td>
                <% end %>
                <td>
                  <% status_class = case movimentacao.status
                     when 'em_andamento' then 'warning'
                     when 'concluida' then 'success'
                     when 'cancelada' then 'danger'
                     end %>
                  <span class="badge badge-<%= status_class %>">
                    <%= movimentacao.status.humanize %>
                  </span>
                </td>
                <td>
                  <%= movimentacao.equipamentos_recebidos_count %> / <%= movimentacao.total_equipamentos %>
                  <% if movimentacao.equipamentos_pendentes_count > 0 %>
                    <span class="badge badge-warning">
                      <%= movimentacao.equipamentos_pendentes_count %> pendente(s)
                    </span>
                  <% end %>
                </td>
                <td><%= movimentacao.data_movimentacao&.strftime("%d/%m/%Y %H:%M") %></td>
                <td>
                  <%= link_to movimentacao_equipamento_path(movimentacao), class: "btn btn-sm btn-info", title: "Ver Detalhes" do %>
                    <i class="fas fa-eye"></i>
                  <% end %>
                  
                  <% if movimentacao.pode_ser_cancelada? && current_user.has_role?(:tec_serv_ti) && current_user.id == movimentacao.user_id %>
                    <%= link_to cancelar_movimentacao_equipamento_path(movimentacao), 
                        method: :patch, 
                        class: "btn btn-sm btn-danger", 
                        title: "Cancelar Movimentação",
                        data: { confirm: "Tem certeza que deseja cancelar esta movimentação? Esta ação não pode ser desfeita." } do %>
                      <i class="fas fa-times"></i>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      
      <div class="d-flex justify-content-center">
        <%= paginate @movimentacoes %>
      </div>
    <% else %>
      <div class="alert alert-info">
        <i class="fas fa-info-circle"></i>
        <% if current_user.has_role?(:tec_serv_ti) %>
          Nenhuma movimentação encontrada.
        <% elsif current_user.has_role?(:req_serv_ti) %>
          Você não possui movimentações pendentes.
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<% content_for :javascripts do %>
<script>
  $(function(){
    function bindAutocompleteWithHidden(inputSelector, hiddenSelector, url){
      $(inputSelector).autocomplete({
        minLength: 0,
        appendTo: 'body',
        position: { my: "left top", at: "left bottom", collision: "none" },
        source: function(request, response){
          $.getJSON(url, { term: request.term }, function(data){
            response($.map(data, function(item){ return { label: item.value, value: item.value, id: item.id }; }));
          });
        },
        select: function(event, ui){
          $(hiddenSelector).val(ui.item.id);
          $(inputSelector).val(ui.item.value).trigger('change');
          return false;
        },
        change: function(event, ui){ if(!ui.item){ $(hiddenSelector).val(''); } }
      }).autocomplete("widget").addClass("ui-autocomplete-modal");

      $(inputSelector).on('focus', function(){ $(this).autocomplete("search", ""); });
      $(inputSelector).on('input', function(){ if($(this).val() === '') { $(hiddenSelector).val(''); } });
    }

    bindAutocompleteWithHidden('.js-autocomplete-unidade', '#mov_equip_unidade_id', '/autocompletes/unidades');
    bindAutocompleteWithHidden('.js-autocomplete-usuario-criador', '#mov_equip_user_id', '/autocompletes/usuarios');
    bindAutocompleteWithHidden('.js-autocomplete-usuario-responsavel', '#mov_equip_responsavel_id', '/autocompletes/usuarios');

    $('<style>')
      .prop('type', 'text/css')
      .html(`
        .ui-autocomplete-modal {
          z-index: 9999 !important;
          max-height: 200px;
          overflow-y: auto;
          overflow-x: hidden;
        }
        .ui-autocomplete-modal .ui-menu-item { padding: 8px 12px; border-bottom: 1px solid #eee; cursor: pointer; }
        .ui-autocomplete-modal .ui-menu-item:hover { background-color: #f8f9fa; }
        .ui-autocomplete-modal .ui-menu-item:last-child { border-bottom: none; }
      `)
      .appendTo('head');
  })
</script>
<% end %>