config/routes.rb
Rails.application.routes.draw do
  resources :tarefas do
    collection do
      get :atualizar_status
    end
  end

  resources :acoes do
    resources :etapas
    get 'relatorio', on: :member, defaults: { format: :pdf }
    get 'relatorio_geral', on: :collection, defaults: { format: :pdf }
    get 'relatorio_geral_simplificado', on: :collection, defaults: { format: :pdf }
  end
  
  namespace :transporte_escolar do
    resources :servicos do
      collection do
        post :search
      end
    end
  end
  namespace :transporte_escolar do
    resources :contratos
  end
  namespace :transporte_escolar do
    resources :veiculos
  end
  namespace :transporte_escolar do
    resources :condutores
  end
  namespace :transporte_escolar do
    resources :transportadores
  end
  namespace :transporte_escolar do
    resources :escolas
  end
  namespace :transporte_escolar do
    resources :municipios
  end
  resources :incidentes do
    member do
      get 'finalizar'
      put 'salvar'
    end
  end

  resources :mensagens do
    get 'mensagens_diretas', on: :collection
    get 'refresh', on: :collection
    post 'js_create', on: :collection
    member do
      get 'new_image'
      put 'update_image'
    end
    get 'imagem', on: :collection
  end

  resources :autocompletes, only: [] do
    collection do
      get :problemas_ti
      get :cargos
      get :funcoes
      get :unidades
      get :usuarios
      get :estados
      get :municipios
      get :permissoes_drive
      get :perfis
    end
  end

  resources :cargos
  resources :tipo_unidades
  resources :problema_tis
  resources :tipo_problema_tis
  resources :equipamentos do
    member do
      patch :transferir
      patch :alterar_status
      patch :remover_de_kit
    end
    collection do
      get :buscar
      get :relatorio
      get :verificar_kit
      get :exportar_excel
      get :autocomplete_marcas
      get :autocomplete_modelos
      get :autocomplete_identificacoes_kit
      get :autocomplete_contratos
      get :autocomplete_processos
    end
  end

  resources :movimentacao_equipamentos do
    member do
      patch :receber_equipamento
      patch :cancelar
    end
    collection do
      get :buscar_equipamentos
      get :buscar_usuarios_unidade
    end
  end
  resources :requisicao_tis do
    member do
      get 'finalizar'
      put 'salvar'
    end
  end

  namespace :nuinfo do
    resources :requisicao_tis, only: [:index, :show] do
      get 'pegar'
      collection do
        get 'acompanhamento'
        get 'refresh_acompanhamento'
        get 'em_atendimento'
        get 'estatisticas'
        post 'buscar_estatisticas'
      end
      member do
        get 'concluir'
        get 'trocar_tecnico'
        put 'salvar'
        put 'salvar_troca_tecnico'
      end
    end
  end

  get 'patio/index'
  get 'patio/entrada'
  get 'patio/saida'

  namespace :useget do
    resources :requisicao_transportes, only: [:index, :show] do
      get 'aprovar'
      member do
        get 'reagendar'
        put 'salvar_reagendamento'
      end
      collection do
        get 'acompanhamento'
        get 'refresh_acompanhamento'
      end
      member do
        get 'negar'
        put 'salvar_negacao'
      end
    end
  end

  resources :servico_transportes, only: [:show, :new, :create, :edit, :update]

  resources :destinos
  resources :passageiros
  resources :requisicao_transportes do
    member do
      get 'avaliar_reagendamento'
      put 'aprovar_reagendamento'
      put 'negar_reagendamento'
    end
  end
  resources :veiculos
  resources :motoristas
  get 'home/index'

  get 'perfil/index'
  put 'perfil/update'
  get 'perfil/alterar_senha'
  put 'perfil/salvar_senha'

  resources :usuarios do
    member do
      get 'resetar_senha'
      get 'tornar_requisitante_transporte'
      get 'tornar_tecnico_transporte'
    end
  end

  resources :unidades
  resources :funcoes do
    get 'autocomplete', on: :collection
  end

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/transporte_escolar.rb
module TransporteEscolar
  def self.table_name_prefix
    'transporte_escolar_'
  end
end

app/models/transporte_escolar/condutor.rb
class TransporteEscolar::Condutor < ApplicationRecord
  # fields
  # t.string :nome
  # t.string :cpf
  # t.string :tipo
  # t.string :permissao
  # t.string :vencimento
  # t.references :municipio, null: false, foreign_key: { to_table: :transporte_escolar_municipios }
  # t.string :bairro
  # t.string :logradouro
  # t.string :numero
  # t.string :cep

  belongs_to :municipio, class_name: 'TransporteEscolar::Municipio'

  has_many :veiculos, class_name: "TransporteEscolar::Veiculo", dependent: :restrict_with_error

  validates_presence_of :nome, :cpf, :tipo, :permissao, :municipio_id
  validates_uniqueness_of :cpf

  enum tipo: { "Rodoviário": 1, "Hidroviário": 2 }

  before_save :upcase_fields

  def upcase_fields
    self.nome.upcase! if self.nome
    self.permissao.upcase! if self.permissao
    self.bairro.upcase!
    self.logradouro.upcase!
    self.numero.upcase!
  end
end

app/models/transporte_escolar/escola.rb
class TransporteEscolar::Escola < ApplicationRecord
  # fiels:
  # t.string "codigo"
  # t.string "nome", presence, unique
  # t.bigint "municipio_id", references, presence
  # t.string "bairro"
  # t.string "logradouro"
  # t.string "numero"
  # t.string "cep"

  belongs_to :municipio, class_name: 'TransporteEscolar::Municipio'
  
  validates_presence_of :nome, :municipio_id
  validates_uniqueness_of :nome

  before_save :upcase_fields

  def upcase_fields
    self.nome.upcase!
    self.bairro.upcase!
    self.logradouro.upcase!
    self.numero.upcase!
  end

end

app/controllers/transporte_escolar/condutores_controller.rb
# app/controllers/transporte_escolar/condutores_controller.rb

class TransporteEscolar::CondutoresController < ApplicationController
  before_action :verify_permission 
  before_action :set_condutor, only: %i[ show edit update destroy ]
  before_action :load_municipios, only: %i[ new edit create update ]
  before_action :load_tipos, only: %i[ new edit create update ]

  def index
    @condutores = TransporteEscolar::Condutor.all
  end

  def show
  end

  def new
    @condutor = TransporteEscolar::Condutor.new
  end

  def edit
  end

  def create
    @condutor = TransporteEscolar::Condutor.new(condutor_params)

    respond_to do |format|
      if @condutor.save
        flash[:success] = "Condutor criado."
        format.json { render :show, status: :created, location: @condutor }
        format.js { render :create, status: :created  }
      else
        flash.now[:error] = "Opss! Algo deu errado."
        format.json { render json: @condutor.errors, status: :unprocessable_entity }
        format.js { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @condutor.update(condutor_params)
        flash[:success] = "Condutor atualizado."
        format.json { render :show, status: :ok, location: @condutor }
        format.js { render :update, status: :created  }
      else
        flash.now[:error] = "Opss! Algo deu errado."
        format.json { render json: @condutor.errors, status: :unprocessable_entity }
        format.js { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @condutor.destroy
      flash[:success] = "Condutor excluído"
    else
      flash[:error] = "Opss! Algo deu errado."
    end

    respond_to do |format|
      format.html { redirect_to transporte_escolar_condutores_url }
      format.json { head :no_content }
    end
  end

  private
    def set_condutor
      @condutor = TransporteEscolar::Condutor.find(params[:id])
    end

    def condutor_params
      params.require(:transporte_escolar_condutor).permit(:nome, :cpf, :tipo, :permissao, :vencimento, :municipio_id, :bairro, :logradouro, :numero, :cep)
    end

    def verify_permission
      if !current_user.has_role? :ges_tp_es and !current_user.has_role? :tec_tp_es and !current_user.has_role? :master
        flash[:info] = "Você não possui as permissões necessárias para acessar!"
        redirect_to home_index_path
      end
    end

    def load_municipios
      @municipios = TransporteEscolar::Municipio.order(nome: :asc).all.map{ |m| [m.nome_tipo, m.id] }
    end

    def load_tipos
      @tipos = TransporteEscolar::Condutor.tipos.keys
    end
end

app/controllers/transporte_escolar/contratos_controller.rb
# app/controllers/transporte_escolar/contratos_controller.rb

class TransporteEscolar::ContratosController < ApplicationController
  before_action :verify_permission
  before_action :set_contrato, only: [:show, :edit, :update, :destroy]
  before_action :load_transportadores, only: %i[ new edit create update ]
  before_action :load_escolas, only: %i[ new edit create update ]
  before_action :load_veiculos, only: %i[ new edit create update ]

  def index
    @contratos = TransporteEscolar::Contrato.order('created_at DESC').all
  end

  def show
  end

  def new
    @contrato = TransporteEscolar::Contrato.new
  end

  def edit
  end

  def create
    @contrato = TransporteEscolar::Contrato.new(contrato_params)
    
    respond_to do |format|
      if @contrato.save!
        flash[:success] = "Contrato criado com sucesso."
        format.js { render :create, status: :created  }
        format.json { render :show, status: :created, location: @contrato }
      else
        flash.now[:error] = "Opss! Algo deu errado."
        format.js { render :new }
        format.json { render json: @contrato.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contrato.update(contrato_params)
        flash[:success] = "Contrato atualizado com sucesso."
        format.js { render :update, status: :created  }
        format.json { render :show, status: :ok, location: @contrato }
      else
        flash.now[:error] = "Opss! Algo deu errado."
        format.js { render :edit }
        format.json { render json: @contrato.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @contrato.destroy
      flash[:success] = "Contrato excluído com sucesso."
    else
      error_messages = @contrato.errors.full_messages.to_sentence
      flash[:info] = error_messages
      flash[:error] = "Opss! Algo deu errado."
    end

    respond_to do |format|
      format.html { redirect_to transporte_escolar_contratos_url }
      format.json { head :no_content }
    end
  end

  private
    def set_contrato
      @contrato = TransporteEscolar::Contrato.find(params[:id])
    end

    def contrato_params
      params.require(:transporte_escolar_contrato).permit(:codigo, :rota, :descricao, :inicio, :fim, 
        :valor_total, :valor_diaria, :transportador_id, :escola_id, :veiculo_id)
    end

    def verify_permission
      if !current_user.has_role? :ges_tp_es and !current_user.has_role? :master 
        flash[:info] = "Você não possui as permissões necessárias para acessar!"
        redirect_to home_index_path
      end
    end

    def load_transportadores
      @transportadores = TransporteEscolar::Transportador.order(nome: :asc).all.map{ |t| [t.nome_ou_razao_social, t.id, {:nome_ou_razao_social => t.nome.downcase}] }
    end

    def load_escolas
      @escolas = TransporteEscolar::Escola.order(nome: :asc).all.map{ |e| [e.nome,  e.id, {:nome => e.nome.downcase}] }
    end

    def load_veiculos
      @veiculos = TransporteEscolar::Veiculo.order(identificacao: :asc).all.map{ |v| [v.identificacao, v.id, {:identificacao => v.identificacao}] }
    end
end

app/controllers/transporte_escolar/escolas_controller.rb
class TransporteEscolar::EscolasController < ApplicationController
  before_action :verify_permission 
  before_action :set_escola, only: %i[ show edit update destroy ]
  before_action :load_municipios, only: %i[ new edit create update ]

  def index
    @escolas = TransporteEscolar::Escola.all
  end

  def show
  end

  def new
    @escola = TransporteEscolar::Escola.new
  end

  def edit
  end

  def create
    @escola = TransporteEscolar::Escola.new(escola_params)

    respond_to do |format|
      if @escola.save
        flash[:success] = "Escola criada."
        format.json { render :show, status: :created, location: @escola }
        format.js {render :create, status: :created  }
      else
        flash.now[:error] = "Opss! Algo deu errado."
        format.json { render json: @escola.errors, status: :unprocessable_entity }
        format.js { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @escola.update(escola_params)
        flash[:success] = "Escola atualizada."
        format.json { render :show, status: :ok, location: @escola }
        format.js {render :update, status: :created  }
      else
        flash.now[:error] = "Opss! Algo deu errado."
        format.json { render json: @escola.errors, status: :unprocessable_entity }
        format.js { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @escola.destroy
      flash[:success] = "Escola excluida"
    else
      flash[:error] = "Opss! Algo deu errado."
    end

    respond_to do |format|
      format.html { redirect_to escolas_url }
      format.json { head :no_content }
    end
  end

  private
    def set_escola
      @escola = TransporteEscolar::Escola.find(params[:id])
    end

    def escola_params
      params.require(:transporte_escolar_escola).permit(:codigo, :nome, :municipio_id, :bairro, :logradouro, :numero, :cep)
    end

    def verify_permission
      if !current_user.has_role? :ges_tp_es and !current_user.has_role? :tec_tp_es and !current_user.has_role? :master 
        flash[:info] = "Você não possui as permissões necessárias para acessar!"
        redirect_to home_index_path
      end
    end

    def load_municipios
      @municipios = TransporteEscolar::Municipio.order(nome: :asc).all.map{ |m| [m.nome_tipo, m.id, {:nome => m.nome.downcase}] }
    end
end

app/controllers/transporte_escolar/municipios_controller.rb
class TransporteEscolar::MunicipiosController < ApplicationController
  before_action :set_transporte_escolar_municipio, only: %i[ show edit update destroy ]
  before_action :verify_permission 

  # GET /transporte_escolar/municipios or /transporte_escolar/municipios.json
  def index
    @transporte_escolar_municipios = TransporteEscolar::Municipio.all
  end

  # GET /transporte_escolar/municipios/1 or /transporte_escolar/municipios/1.json
  def show
  end

  # GET /transporte_escolar/municipios/new
  def new
    @transporte_escolar_municipio = TransporteEscolar::Municipio.new
  end

  # GET /transporte_escolar/municipios/1/edit
  def edit
  end

  # POST /transporte_escolar/municipios or /transporte_escolar/municipios.json
  def create
    @transporte_escolar_municipio = TransporteEscolar::Municipio.new(transporte_escolar_municipio_params)

    respond_to do |format|
      if @transporte_escolar_municipio.save
        format.html { redirect_to transporte_escolar_municipio_url(@transporte_escolar_municipio), notice: "Municipio was successfully created." }
        format.json { render :show, status: :created, location: @transporte_escolar_municipio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transporte_escolar_municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transporte_escolar/municipios/1 or /transporte_escolar/municipios/1.json
  def update
    respond_to do |format|
      if @transporte_escolar_municipio.update(transporte_escolar_municipio_params)
        format.html { redirect_to transporte_escolar_municipio_url(@transporte_escolar_municipio), notice: "Municipio was successfully updated." }
        format.json { render :show, status: :ok, location: @transporte_escolar_municipio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transporte_escolar_municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transporte_escolar/municipios/1 or /transporte_escolar/municipios/1.json
  def destroy
    if @transporte_escolar_municipio.destroy
      flash[:success] = "Municipio apagado"
    else
      flash[:error] = "Opss! Algo deu errado."
    end
    respond_to do |format|
      format.html { redirect_to transporte_escolar_municipios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transporte_escolar_municipio
      @transporte_escolar_municipio = TransporteEscolar::Municipio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transporte_escolar_municipio_params
      params.require(:transporte_escolar_municipio).permit(:nome, :tipo)
    end

    def verify_permission
      if !current_user.has_role? :ges_tp_es and !current_user.has_role? :tec_tp_es and !current_user.has_role? :master 
        flash[:info] = "Você não possui as permissões necessárias para acessar!"
        redirect_to home_index_path
      end
    end
end

app/helpers/transporte_escolar/condutores_helper.rb
module TransporteEscolar::CondutoresHelper
end

app/helpers/transporte_escolar/contratos_helper.rb
module TransporteEscolar::ContratosHelper
end

app/helpers/transporte_escolar/escolas_helper.rb
module TransporteEscolar::EscolasHelper
end

app/helpers/transporte_escolar/municipios_helper.rb
module TransporteEscolar::MunicipiosHelper
end

app/helpers/transporte_escolar/servicos_helper.rb
module TransporteEscolar::ServicosHelper
end

app/views/transporte_escolar/servicos/_form.html.erb
<!-- app/views/transporte_escolar/servicoes/_form.html.erb -->

<div class="modal-body">

  <%= form_for @servico, remote: true do |f| %>
    
    <% if @servico.errors.any? %>
      <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-ban"></i> Ops! Algo deu errado.</h5>
      </div>
    <% end %>

    <div class="form-group">
      <%= label_tag "Contrato (Número ou Código)" %>
      <%= text_field_tag '',(@servico.contrato&.codigo if @servico.contrato&.codigo), class: "form-control", readonly: true %>
    </div>

    <div class="form-group">
      <%= label_tag "Serviço (Número ou Código)" %>
      <%= text_field_tag '',(@servico.numero), class: "form-control", readonly: true %>
    </div>

    <div class="form-group">
      <%= label_tag "Referência (Mês/Ano)" %>
      <%= text_field_tag '',(@servico.ano_mes if @servico.ano_mes), class: "form-control", readonly: true %>
    </div>

    <div class="form-group">
      <%= label_tag "Valor Integral" %>
      <%= text_field_tag '',(@servico.contrato&.valor_total&.real_contabil if @servico.contrato&.valor_total&.real_contabil), class: "form-control", readonly: true %>
    </div>

    <div class="form-group">
      <%= label_tag "Valor Diária" %>
      <%= text_field_tag '',(@servico.contrato&.valor_diaria&.real_contabil if @servico.contrato&.valor_diaria&.real_contabil), class: "form-control", readonly: true %>
    </div>

    <div class="form-group">
      <%= f.label :diarias, "Número de diárias" %>
      <%= f.number_field :diarias, class: "form-control", required: true, min: 0, max: 31 %>
      <%= has_error(@servico, :diarias) %>
    </div>

    <div class="form-group">
      <%= f.label :status, "Status do Serviço" %>
      <%= f.select :status, @status, { include_blank: true }, { class: "form-control js-searchable select2-status", required: true } %>
      <%= has_error(@servico, :status) %>
    </div>

    <div class="form-group">
      <%= f.label :nota, "Enviou Nota?" %>
      <div class="custom-control custom-switch">
        <%= f.check_box :nota, class: "custom-control-input", id: "customSwitchNota" %>
        <%= f.label :nota, "", class: "custom-control-label", for: "customSwitchNota" %>
      </div>
      <%= has_error(@servico, :nota) %>
    </div>

    <div class="form-group">
      <%= f.label :boletim, "Enviou Boletim?" %>
      <div class="custom-control custom-switch">
        <%= f.check_box :boletim, class: "custom-control-input", id: "customSwitchBoletim" %>
        <%= f.label :boletim, "", class: "custom-control-label", for: "customSwitchBoletim" %>
      </div>
      <%= has_error(@servico, :boletim) %>
    </div>

    <div class="modal-footer">
      <button type="submit" class="btn btn-success" data-disable-with="Salvar"><i class="icon fa fa-check"></i> Salvar</button>
      <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="icon fas fa-ban"></i> Cancelar</button>
    </div>

  <% end %>    

  <script>
    $(document).ready(function() {
      
      $('.js-searchable').select2({
        placeholder: "Selecione",
        allowClear: true,
        theme: 'bootstrap',
        width: '100%'
      }); 
    });
  </script>

</div>

app/views/transporte_escolar/servicos/_search_form.html.erb
<div class="card card-default">
  <div class="card-header">
    <h3 class="card-title">Formulário de pesquisa</h3>
  </div>

  <%= form_tag search_transporte_escolar_servicos_path, class: 'form-horizontal' do %>
    <div class="card-body">
      <div class="form-row">
        
        <div class="col-md-2">          
          <%= select_tag(:ano_mes, options_for_select(@datas, (@ano_mes ? @ano_mes : '')), prompt: "Selecione uma opção", class: 'form-control js-searchable') %>
        </div>

        <div class="col-md-3">
          <%= select_tag(:municipio, options_for_select(@municipios, (@municipio ? @municipio : '')), prompt: "Selecione uma opção", class: 'form-control js-searchable') %>
        </div>
        
        <div class="col-md-3">
          <%= select_tag(:escola, options_for_select(@escolas, (@escola ? @escola : '')), prompt: "Selecione uma opção", class: 'form-control js-searchable') %>
        </div>

        <div class="col-md-3">
          <%= select_tag(:transportador, options_for_select(@transportadores, (@transportador ? @transportador : '')), prompt: "Selecione uma opção", class: 'form-control js-searchable') %>
        </div>

        <div class="col-md-1">
          <button type="submit" class="btn btn-info">Buscar</button>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/transporte_escolar/servicos/_servico.html.erb
<!-- app/views/transporte_escolar/servicoes/_servico.html.erb -->
<%
  tr_class = if servico.pendencias.present?
               "table-warning"
             elsif servico.status == "Pago" && !servico.pendencias.present?
               "table-success"
             else
               ""
             end
%>
<tr class="<%= tr_class %>">
  <td><%= index + 1 %></td> 
  <td><%= link_to servico.contrato&.codigo, servico.contrato ? servico.contrato : '#', remote: true %></td>
  <td><%= link_to servico.contrato&.escola&.nome, servico.contrato&.escola ? servico.contrato&.escola : '#', remote: true %></td>
  <td><%= servico.contrato&.escola&.municipio&.nome_tipo %></td>
  <td><%= link_to servico.contrato&.veiculo&.tipo_identificacao, servico.contrato&.veiculo ? servico.contrato&.veiculo : '#', remote: true %></td>
  <td><%= link_to servico.contrato&.transportador&.nome_ou_razao_social, servico.contrato&.transportador ? servico.contrato&.transportador : '#', remote: true %></td>
  <td><%= servico.contrato&.valor_total&.real_contabil %></td>
  <td><%= servico.contrato&.valor_diaria&.real_contabil %></td>
  <td><%= servico.diarias ? servico.diarias : 0 %></td>
  <td><%= servico.calcular_valor.real_contabil %></td>
  <td><%= servico.status %></td>
  <td>
    <%= link_to servico, class: "btn btn-sm btn-default", title: "Ver", remote: true do %>
      <i class="fas fa-eye"></i>
    <% end %>
    <%= link_to edit_transporte_escolar_servico_path(servico), class: "btn btn-sm btn-primary", title: "Editar", remote: true  do %>
      <i class="fas fa-edit"></i>
    <% end %>
    <%= link_to servico, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-sm btn-danger", title: "Excluir"  do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </td>
</tr> 

app/views/transporte_escolar/servicos/index.html.erb
<!-- app/views/transporte_escolar/servicoes/index.html.erb -->

<% content_for :title do %>
  <i class="fa fa-info"></i> Serviços
<% end %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active"><a href="<%= transporte_escolar_servicos_url %>">Serviços</a></li>
<% end %>
<% content_for :sub_title do %>
  Lista de servicoes
<% end %>
<% content_for :buttons do %>
  <%= link_to new_transporte_escolar_servico_path, class: "btn btn-sm btn-success", title: "Novo Serviço", remote: true do %>
    <i class="fas fa-plus"></i> Novo
  <% end %>
<% end %>

<%= render "search_form", servicos: @servicos, ano_mes: @ano_mes %>

<div class="row">
  <div class="info-box col-lg">
    <span class="info-box-icon bg-primary"><i class="fa fa-calendar"></i></span>
    <div class="info-box-content">
      <span class="info-box-number"><%= @ano_mes.to_date.strftime("%B") %></span>
      <span class="info-box-number"><%=  @ano_mes.to_date.year %></span>
    </div>
  </div>
  
  <div class="info-box col-lg">
    <span class="info-box-icon bg-primary"><i class="fa fa-map"></i></span>
    <div class="info-box-content">
      <span class="info-box-number"><%= @escola ? TransporteEscolar::Escola.find(@escola)&.nome : 'Escola: Todas' %></span>
      <span class="info-box-number"><%= @municipio ? TransporteEscolar::Municipio.find(@municipio)&.nome : 'Municipio: Todos' %></span>
    </div>
  </div>

  <div class="info-box col-lg">
    <span class="info-box-icon bg-primary"><i class="fa fa-car"></i></span>
    <div class="info-box-content">
      <span class="info-box-number"><%= @transportador ? TransporteEscolar::Transportador.find(@transportador)&.nome_ou_razao_social : 'Transportador: Todos' %></span>
      <span class="info-box-number"><%= @transportador ? TransporteEscolar::Transportador.find(@transportador)&.cpf_ou_cnpj : '' %></span>
    </div>
  </div>

  <div class="info-box col-lg">
    <span class="info-box-icon bg-warning"><i class="fa fa-money"></i></span>
    <div class="info-box-content">
      <span class="info-box-number">Valor Estimado</span>
      <span class="info-box-number"><%= @servicos_valor_estimado.real_contabil  %></span>
    </div>
  </div>

  <div class="info-box col-lg">
    <span class="info-box-icon bg-danger"><i class="fa fa-money"></i></span>
    <div class="info-box-content">
      <span class="info-box-number">Valor Trabalhado</span>
      <span class="info-box-number"><%= @servicos_com_valor.sum(&:valor_total_diarias).real_contabil %></span>
    </div>
  </div>
</div>

<table id="data-table" class="table table-bordered table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Contrato</th>
      <th>Escola</th>
      <th>Município</th>
      <th>Veículo</th>
      <th>Transportador</th>
      <th>Valor Integral</th>
      <th>Valor Diárias</th>
      <th>Dias TB</th>
      <th>Valor</th>
      <th>Status</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody id="data-table-body">
    <% @servicos.each_with_index do |servico, index| %>
      <%= render 'servico', servico: servico, index: index %>
    <% end %>
  </tbody>
</table>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function() {
      $('.js-searchable').select2({
        placeholder: "Selecione uma opção",
        allowClear: true,
        theme: 'bootstrap',
        width: '100%'
      });
    });
  </script>
<% end %>

app/views/transporte_escolar/servicos/update.js.erb
location.reload();