config/routes.rb
Rails.application.routes.draw do
  resources :tarefas do
    collection do
      get :atualizar_status
    end
  end

  resources :acoes do
    resources :etapas
    get 'relatorio', on: :member, defaults: { format: :pdf }
    get 'relatorio_geral', on: :collection, defaults: { format: :pdf }
    get 'relatorio_geral_simplificado', on: :collection, defaults: { format: :pdf }
  end
  
  namespace :transporte_escolar do
    resources :servicos do
      collection do
        post :search
      end
    end
  end
  namespace :transporte_escolar do
    resources :contratos
  end
  namespace :transporte_escolar do
    resources :veiculos
  end
  namespace :transporte_escolar do
    resources :condutores
  end
  namespace :transporte_escolar do
    resources :transportadores
  end
  namespace :transporte_escolar do
    resources :escolas
  end
  namespace :transporte_escolar do
    resources :municipios
  end
  resources :incidentes do
    member do
      get 'finalizar'
      put 'salvar'
    end
  end

  resources :mensagens do
    get 'mensagens_diretas', on: :collection
    get 'refresh', on: :collection
    post 'js_create', on: :collection
    member do
      get 'new_image'
      put 'update_image'
    end
    get 'imagem', on: :collection
  end

  resources :autocompletes, only: [] do
    collection do
      get :problemas_ti
      get :cargos
      get :funcoes
      get :unidades
      get :usuarios
      get :estados
      get :municipios
      get :permissoes_drive
      get :perfis
    end
  end

  resources :cargos
  resources :tipo_unidades
  resources :problema_tis
  resources :tipo_problema_tis
  resources :equipamentos do
    member do
      patch :transferir
      patch :alterar_status
      patch :remover_de_kit
    end
    collection do
      get :buscar
      get :relatorio
      get :verificar_kit
      get :exportar_excel
      get :autocomplete_marcas
      get :autocomplete_modelos
      get :autocomplete_identificacoes_kit
      get :autocomplete_contratos
      get :autocomplete_processos
    end
  end

  resources :movimentacao_equipamentos do
    member do
      patch :receber_equipamento
      patch :cancelar
    end
    collection do
      get :buscar_equipamentos
      get :buscar_usuarios_unidade
    end
  end
  resources :requisicao_tis do
    member do
      get 'finalizar'
      put 'salvar'
    end
  end

  namespace :nuinfo do
    resources :requisicao_tis, only: [:index, :show] do
      get 'pegar'
      collection do
        get 'acompanhamento'
        get 'refresh_acompanhamento'
        get 'em_atendimento'
        get 'estatisticas'
        post 'buscar_estatisticas'
      end
      member do
        get 'concluir'
        get 'trocar_tecnico'
        put 'salvar'
        put 'salvar_troca_tecnico'
      end
    end
  end

  get 'patio/index'
  get 'patio/entrada'
  get 'patio/saida'

  namespace :useget do
    resources :requisicao_transportes, only: [:index, :show] do
      get 'aprovar'
      member do
        get 'reagendar'
        put 'salvar_reagendamento'
      end
      collection do
        get 'acompanhamento'
        get 'refresh_acompanhamento'
      end
      member do
        get 'negar'
        put 'salvar_negacao'
      end
    end
  end

  resources :servico_transportes, only: [:show, :new, :create, :edit, :update]

  resources :destinos
  resources :passageiros
  resources :requisicao_transportes do
    member do
      get 'avaliar_reagendamento'
      put 'aprovar_reagendamento'
      put 'negar_reagendamento'
    end
  end
  resources :veiculos
  resources :motoristas
  get 'home/index'

  get 'perfil/index'
  put 'perfil/update'
  get 'perfil/alterar_senha'
  put 'perfil/salvar_senha'

  resources :usuarios do
    member do
      get 'resetar_senha'
      get 'tornar_requisitante_transporte'
      get 'tornar_tecnico_transporte'
    end
  end

  resources :unidades
  resources :funcoes do
    get 'autocomplete', on: :collection
  end

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/problema_ti.rb
class ProblemaTi < ApplicationRecord
  belongs_to :tipo_problema_ti
  has_many :requisicao_tis
end

app/controllers/problema_tis_controller.rb
class ProblemaTisController < ApplicationController
  before_action :set_problema_ti, only: %i[ show edit update destroy ]
  before_action :load_problemas, only: %i[ new edit update create ]

  # GET /problema_tis or /problema_tis.json
  def index
    @problema_tis = ProblemaTi.all
  end

  # GET /problema_tis/1 or /problema_tis/1.json
  def show
  end

  # GET /problema_tis/new
  def new
    @problema_ti = ProblemaTi.new
  end

  # GET /problema_tis/1/edit
  def edit
  end

  # POST /problema_tis or /problema_tis.json
  def create
    @problema_ti = ProblemaTi.new(problema_ti_params)

    respond_to do |format|
      if @problema_ti.save
        flash[:success] = "Problema criado."
        format.js {render :create, status: :created  }
      else
        flash.now[:error] = "Opss! Algo deu errado."
        format.js { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problema_tis/1 or /problema_tis/1.json
  def update
    respond_to do |format|
      if @problema_ti.update(problema_ti_params)
        flash[:success] = "Problema atualizado."
        format.js {render :update, status: :created  }
      else
        flash.now[:error] = "Opss! Algo deu errado."
        format.js { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problema_tis/1 or /problema_tis/1.json
  def destroy
    if @problema_ti.destroy
      flash[:success] = "Problema excluido"
    else
      flash[:error] = "Opss! Algo deu errado."
    end
    respond_to do |format|
      format.html { redirect_to problema_tis_url }
    end  

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problema_ti
      @problema_ti = ProblemaTi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def problema_ti_params
      params.require(:problema_ti).permit(:nome, :descricao, :status, :tipo_problema_ti_id)
    end

    def load_problemas
      @tipo_problemas = TipoProblemaTi.order(nome: :asc).map{ |p| [p.nome, p.id, {:nome => p.nome.downcase}] }
    end
end

app/helpers/problema_tis_helper.rb
module ProblemaTisHelper
end

app/views/problema_tis/_form.html.erb
<div class="modal-body">

  <%= form_for @problema_ti, remote: true do |f| %>
    
    <% if @problema_ti.errors.any? %>
      <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-ban"></i> Ops! Algo deu errado.</h5>
      </div>
    <% end %>


    <div class="form-group">
      <%= f.label :nome %>
      <%= f.text_field :nome, autofocus: true, autocomplete: "Nome", placeholder: "Digite o nome da função", class: "form-control", required: true %>
      <%= has_error(@problema_ti, :nome) %>
    </div>

    <div class="form-group">
      <%= f.label :descricao, "Descrição" %>
      <%= f.text_field :descricao, autofocus: true, autocomplete: "Descrição", placeholder: "Digite a descrição do problema", class: "form-control", required: true %>
      <%= has_error(@problema_ti, :descricao) %>
    </div>

    <div class="form-group">
      <%= f.label :tipo_problema_ti_id, "Tipo de Problema" %>
      <%= f.select :tipo_problema_ti_id, @tipo_problemas, { include_blank: true }, { class: "form-control js-searchable", required: true } %>  
      <%= has_error(@problema_ti, :tipo_problema_ti_id) %>
    </div>

    <div class="form-group">
      <%= f.label :status, "Ativo?" %>
      <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
        <%= f.hidden_field :status, value: false %>
        <%= f.check_box :status, class: "custom-control-input", id: "customSwitchStatus", unchecked_value: false, checked_value: true %>
        <%= f.label :status, "", class: "custom-control-label", for: "customSwitchStatus" %>
      </div>
      <%= has_error(@problema_ti, :status) %>
    </div>

    
    <div class="modal-footer">
      <button type="submit" class="btn btn-success" data-disable-with="Salvar"><i class="icon fa fa-check"></i> Salvar</button>
      <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="icon fas fa-ban"></i> Cancelar</button>
    </div>

  <% end %>    

</div>

app/views/problema_tis/_problema_ti.html.erb
<tr>
  <td><%= problema_ti.nome %></td>
  <td><%= problema_ti.tipo_problema_ti.nome if problema_ti.tipo_problema_ti %></td>
  <td><%= problema_ti.status ? 'SIM' : 'NÃO' %></td>
  <td>
    <%= link_to problema_ti, class: "btn btn-sm btn-default", title: "Ver"  do %>
      <i class="fas fa-eye"></i>
    <% end %>
    <%= link_to edit_problema_ti_path(problema_ti), class: "btn btn-sm btn-primary", title: "Editar", remote: true  do %>
      <i class="fas fa-edit"></i>
    <% end %>
    <%= link_to problema_ti, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-sm btn-danger", title: "Excluir"  do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </td>
</tr> 

app/views/problema_tis/edit.html.erb
<h1>Editing Problema Ti</h1>

<%= render 'form', problema_ti: @problema_ti %>

<%= link_to 'Show', @problema_ti %> |
<%= link_to 'Back', problema_tis_path %>

app/views/problema_tis/edit.js.erb
$('#form-modal-title').html("<i class='fa fa-plus'></i> Editar Problema")
$('#form-modal-body').html('<%= j render("form") %>')
$('#form-modal').modal('show')

app/views/problema_tis/index.html.erb
<% content_for :title do %>
  <i class="fa fa-sitemap"></i> Problemas
<% end %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active"><a href="<%= unidades_url %>">Problemas</a></li>
<% end %>
<% content_for :sub_title do %>
  Lista de problemas
<% end %>
<% content_for :buttons do %>
  <%= link_to new_problema_ti_path, class: "btn btn-sm btn-success", title: "Novo problema", remote: true do %>
    <i class="fas fa-plus"></i> Novo
  <% end %>
<% end %>

<table id="data-table" class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Tipo problema ti</th>
      <th>Ativo?</th>
      <th></th>
    </tr>
  </thead>
  <tbody id="data-table-body">
    <%= render @problema_tis %>
  </tbody>
</table>

app/views/problema_tis/new.html.erb
<h1>New Problema Ti</h1>

<%= render 'form', problema_ti: @problema_ti %>

<%= link_to 'Back', problema_tis_path %>

app/views/problema_tis/new.js.erb
$('#form-modal-title').html("<i class='fa fa-plus'></i> Novo Problema")
$('#form-modal-body').html('<%= j render("form") %>')
$('#form-modal').modal('show')

app/views/problema_tis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @problema_ti.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @problema_ti.descricao %>
</p>

<p>
  <strong>Tipo problema ti:</strong>
  <%= @problema_ti.tipo_problema_ti_id %>
</p>

<%= link_to 'Edit', edit_problema_ti_path(@problema_ti) %> |
<%= link_to 'Back', problema_tis_path %>