config/routes.rb
Rails.application.routes.draw do
  resources :tarefas do
    collection do
      get :atualizar_status
    end
  end

  resources :acoes do
    resources :etapas
    get 'relatorio', on: :member, defaults: { format: :pdf }
    get 'relatorio_geral', on: :collection, defaults: { format: :pdf }
    get 'relatorio_geral_simplificado', on: :collection, defaults: { format: :pdf }
  end
  
  namespace :transporte_escolar do
    resources :servicos do
      collection do
        post :search
      end
    end
  end
  namespace :transporte_escolar do
    resources :contratos
  end
  namespace :transporte_escolar do
    resources :veiculos
  end
  namespace :transporte_escolar do
    resources :condutores
  end
  namespace :transporte_escolar do
    resources :transportadores
  end
  namespace :transporte_escolar do
    resources :escolas
  end
  namespace :transporte_escolar do
    resources :municipios
  end
  resources :incidentes do
    member do
      get 'finalizar'
      put 'salvar'
    end
  end

  resources :mensagens do
    get 'mensagens_diretas', on: :collection
    get 'refresh', on: :collection
    post 'js_create', on: :collection
    member do
      get 'new_image'
      put 'update_image'
    end
    get 'imagem', on: :collection
  end

  resources :autocompletes, only: [] do
    collection do
      get :problemas_ti
      get :cargos
      get :funcoes
      get :unidades
      get :usuarios
      get :estados
      get :municipios
      get :permissoes_drive
      get :perfis
    end
  end

  resources :cargos
  resources :tipo_unidades
  resources :problema_tis
  resources :tipo_problema_tis
  resources :equipamentos do
    member do
      patch :transferir
      patch :alterar_status
      patch :remover_de_kit
    end
    collection do
      get :buscar
      get :relatorio
      get :verificar_kit
      get :exportar_excel
      get :autocomplete_marcas
      get :autocomplete_modelos
      get :autocomplete_identificacoes_kit
      get :autocomplete_contratos
      get :autocomplete_processos
    end
  end

  resources :movimentacao_equipamentos do
    member do
      patch :receber_equipamento
      patch :cancelar
    end
    collection do
      get :buscar_equipamentos
      get :buscar_usuarios_unidade
    end
  end
  resources :requisicao_tis do
    member do
      get 'finalizar'
      put 'salvar'
    end
  end

  namespace :nuinfo do
    resources :requisicao_tis, only: [:index, :show] do
      get 'pegar'
      collection do
        get 'acompanhamento'
        get 'refresh_acompanhamento'
        get 'em_atendimento'
        get 'estatisticas'
        post 'buscar_estatisticas'
      end
      member do
        get 'concluir'
        get 'trocar_tecnico'
        put 'salvar'
        put 'salvar_troca_tecnico'
      end
    end
  end

  get 'patio/index'
  get 'patio/entrada'
  get 'patio/saida'

  namespace :useget do
    resources :requisicao_transportes, only: [:index, :show] do
      get 'aprovar'
      member do
        get 'reagendar'
        put 'salvar_reagendamento'
      end
      collection do
        get 'acompanhamento'
        get 'refresh_acompanhamento'
      end
      member do
        get 'negar'
        put 'salvar_negacao'
      end
    end
  end

  resources :servico_transportes, only: [:show, :new, :create, :edit, :update]

  resources :destinos
  resources :passageiros
  resources :requisicao_transportes do
    member do
      get 'avaliar_reagendamento'
      put 'aprovar_reagendamento'
      put 'negar_reagendamento'
    end
  end
  resources :veiculos
  resources :motoristas
  get 'home/index'

  get 'perfil/index'
  put 'perfil/update'
  get 'perfil/alterar_senha'
  put 'perfil/salvar_senha'

  resources :usuarios do
    member do
      get 'resetar_senha'
      get 'tornar_requisitante_transporte'
      get 'tornar_tecnico_transporte'
    end
  end

  resources :unidades
  resources :funcoes do
    get 'autocomplete', on: :collection
  end

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/tipo_unidade.rb
class TipoUnidade < ApplicationRecord
end

app/controllers/tipo_unidades_controller.rb
class TipoUnidadesController < ApplicationController
  before_action :set_tipo_unidade, only: %i[ show edit update destroy ]

  # GET /tipo_unidades or /tipo_unidades.json
  def index
    @tipo_unidades = TipoUnidade.all
  end

  # GET /tipo_unidades/1 or /tipo_unidades/1.json
  def show
  end

  # GET /tipo_unidades/new
  def new
    @tipo_unidade = TipoUnidade.new
  end

  # GET /tipo_unidades/1/edit
  def edit
  end

  # POST /tipo_unidades or /tipo_unidades.json
  def create
    @tipo_unidade = TipoUnidade.new(tipo_unidade_params)

    respond_to do |format|
      if @tipo_unidade.save
        format.html { redirect_to tipo_unidade_url(@tipo_unidade), notice: "Tipo unidade was successfully created." }
        format.json { render :show, status: :created, location: @tipo_unidade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tipo_unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_unidades/1 or /tipo_unidades/1.json
  def update
    respond_to do |format|
      if @tipo_unidade.update(tipo_unidade_params)
        format.html { redirect_to tipo_unidade_url(@tipo_unidade), notice: "Tipo unidade was successfully updated." }
        format.json { render :show, status: :ok, location: @tipo_unidade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tipo_unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_unidades/1 or /tipo_unidades/1.json
  def destroy
    @tipo_unidade.destroy

    respond_to do |format|
      format.html { redirect_to tipo_unidades_url, notice: "Tipo unidade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_unidade
      @tipo_unidade = TipoUnidade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tipo_unidade_params
      params.require(:tipo_unidade).permit(:nome)
    end
end

app/helpers/tipo_unidades_helper.rb
module TipoUnidadesHelper
end

app/views/tipo_unidades/_form.html.erb
<%= form_with(model: tipo_unidade, local: true) do |form| %>
  <% if tipo_unidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_unidade.errors.count, "error") %> prohibited this tipo_unidade from being saved:</h2>

      <ul>
        <% tipo_unidade.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tipo_unidades/edit.html.erb
<h1>Editing Tipo Unidade</h1>

<%= render 'form', tipo_unidade: @tipo_unidade %>

<%= link_to 'Show', @tipo_unidade %> |
<%= link_to 'Back', tipo_unidades_path %>

app/views/tipo_unidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo Unidades</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_unidades.each do |tipo_unidade| %>
      <tr>
        <td><%= tipo_unidade.nome %></td>
        <td><%= link_to 'Show', tipo_unidade %></td>
        <td><%= link_to 'Edit', edit_tipo_unidade_path(tipo_unidade) %></td>
        <td><%= link_to 'Destroy', tipo_unidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo Unidade', new_tipo_unidade_path %>

app/views/tipo_unidades/new.html.erb
<h1>New Tipo Unidade</h1>

<%= render 'form', tipo_unidade: @tipo_unidade %>

<%= link_to 'Back', tipo_unidades_path %>

app/views/tipo_unidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @tipo_unidade.nome %>
</p>

<%= link_to 'Edit', edit_tipo_unidade_path(@tipo_unidade) %> |
<%= link_to 'Back', tipo_unidades_path %>